#!/usr/bin/env bash

# Function to get info for a subdomain
# shellcheck disable=SC2086
query_subdomain() {
    local domain=$1
    local subdomain=$2

    dig "$subdomain"."$domain" +short | awk -v sub="$subdomain" '
    {
        print "The subdomain", sub, "is an A record and points to", $1
    }'
}

# Function to get info for default subdomains
# shellcheck disable=SC2086
domain_info() {
    local domain=$1

    for sub in www lb-01 web-01 web-02; do
        query_subdomain "$domain" "$sub"
    done
}

# Ensure the domain parameter is provided
if [ -z "$1" ]; then
    echo "Usage: $0 <domain> [subdomain]"
    exit 1
fi

# Main logic
domain=$1
subdomain=$2

if [ -z "$subdomain" ]; then
    domain_info "$domain"
else
    query_subdomain "$domain" "$subdomain"
fi

