#!/usr/bin/env bash

# Replace a line with multiple lines with sed
sed -i '/location \/redirect_me {/ {
    s/location \/redirect_me {/location \/redirect_me {
    return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }/g
}' /etc/nginx/sites-available/default

# Restart Nginx to apply the changes
service nginx restart
