#!/usr/bin/env bash
#Display "Best school" 10 times and on 9th print "hi"

count=0

while [ $count -lt 10 ];do
	if [ $count -eq 8 ];then
		echo "Best School"
		echo "Hi"
	else
		echo "Best School"
	fi
	((count++))
done

