#!/usr/bin/env bash
#script that gives you information about the school file

file="school"

if [ -e "$file" ];then
	echo "$file exist"
	if [ -s "$file" ];then
		echo "$file is not empty"
	else
		echo "$file is empty"
	fi
	if [ -f "$file" ];then
		echo "$file is a regular file"
	else 
		echo "$file:cannot open '$file' (No such file or directory)"
	fi
else
	echo "$file does not exist"
fi
